import Foundation

enum ComposerMap {
    static let aliases: [String: String] = [
        "bach": "bach", "j.s. bach": "bach", "j. s. bach": "bach",
        "johann sebastian bach": "bach", "bach, johann sebastian": "bach",
        "vivaldi": "vivaldi", "antonio vivaldi": "vivaldi",
        "a. vivaldi": "vivaldi", "vivaldi, antonio": "vivaldi",
        "chopin": "chopin", "f. chopin": "chopin",
        "frederic chopin": "chopin", "frédéric chopin": "chopin",
        "chopin, frederic": "chopin",
        "rachmaninoff": "rachmaninoff", "rachmaninov": "rachmaninoff",
        "s. rachmaninoff": "rachmaninoff", "sergei rachmaninoff": "rachmaninoff",
        "sergei rachmaninov": "rachmaninoff",
        "mozart": "mozart", "w.a. mozart": "mozart", "w. a. mozart": "mozart",
        "wolfgang amadeus mozart": "mozart", "mozart, wolfgang amadeus": "mozart",
        "beethoven": "beethoven", "l.v. beethoven": "beethoven",
        "ludwig van beethoven": "beethoven", "beethoven, ludwig van": "beethoven",
        "schubert": "schubert", "franz schubert": "schubert",
        "f. schubert": "schubert", "schubert, franz": "schubert",
        "schumann": "schumann", "robert schumann": "schumann",
        "r. schumann": "schumann", "schumann, robert": "schumann",
        "brahms": "brahms", "johannes brahms": "brahms",
        "j. brahms": "brahms", "brahms, johannes": "brahms",
        "haydn": "haydn", "joseph haydn": "haydn", "franz joseph haydn": "haydn",
        "haydn, franz joseph": "haydn",
        "handel": "handel", "george frideric handel": "handel",
        "g.f. handel": "handel", "handel, george frideric": "handel",
        "telemann": "telemann", "georg philipp telemann": "telemann",
        "g.p. telemann": "telemann", "telemann, georg philipp": "telemann",
        "liszt": "liszt", "franz liszt": "liszt",
        "f. liszt": "liszt", "liszt, franz": "liszt",
        "mendelssohn": "mendelssohn", "felix mendelssohn": "mendelssohn",
        "f. mendelssohn": "mendelssohn", "mendelssohn, felix": "mendelssohn",
        "tchaikovsky": "tchaikovsky", "tchaikowsky": "tchaikovsky",
        "pyotr ilyich tchaikovsky": "tchaikovsky", "p.i. tchaikovsky": "tchaikovsky",
        "tchaikovsky, pyotr": "tchaikovsky",
        "dvorak": "dvorak", "dvořák": "dvorak",
        "antonin dvorak": "dvorak", "antonín dvořák": "dvorak",
        "dvorak, antonin": "dvorak",
        "debussy": "debussy", "claude debussy": "debussy",
        "c. debussy": "debussy", "debussy, claude": "debussy",
        "grieg": "grieg", "edvard grieg": "grieg",
        "e. grieg": "grieg", "grieg, edvard": "grieg",
    ]

    static let similarity: [String: [String]] = [
        "bach":         ["vivaldi", "handel", "telemann", "scarlatti"],
        "vivaldi":      ["bach", "handel", "corelli"],
        "chopin":       ["rachmaninoff", "liszt", "schumann"],
        "rachmaninoff": ["chopin", "tchaikovsky", "scriabin"],
        "mozart":       ["haydn", "beethoven", "salieri"],
        "beethoven":    ["mozart", "schubert", "brahms"],
        "schubert":     ["beethoven", "schumann", "brahms"],
        "schumann":     ["brahms", "schubert", "liszt"],
        "brahms":       ["beethoven", "schumann", "dvorak"],
        "haydn":        ["mozart", "handel", "telemann"],
        "handel":       ["bach", "telemann", "vivaldi"],
        "telemann":     ["bach", "handel", "vivaldi"],
        "liszt":        ["chopin", "schumann", "brahms"],
        "mendelssohn":  ["schumann", "brahms", "schubert"],
        "tchaikovsky":  ["rachmaninoff", "dvorak", "brahms"],
        "dvorak":       ["brahms", "tchaikovsky", "schubert"],
        "debussy":      ["grieg", "liszt", "schumann"],
        "grieg":        ["debussy", "liszt", "brahms"],
    ]

    static func normalize(_ raw: String) -> String? {
        aliases[raw.lowercased().trimmingCharacters(in: .whitespaces)]
    }
}
